<?php

use App\Models\User;
use Illuminate\Validation\Rule;



return[
    'saveConnectedPersonDetails'=>[
        'type' => 'required',
        'name' => 'required',
        'nature_of_connection' => 'required',
        'pan_option' => 'required',
        'pan' =>'nullable|required_if:pan_option,Yes|size:10|regex:/^[A-Z]{5}\d{4}[A-Z]$/|unique:connected_people',
        'pan_attachment' =>'required_if:pan_option,Yes',
        'declaration_attachment' =>'required_if:pan_option,No',
        'permanent_address' => 'required_if:type,individual',
        'correspondence_address' => 'required_if:type,individual',
        'email' => 'required|string',
        'mobile' => 'required|string',
        'designation' => 'required_if:type,individual',
        'demat_account_number' => 'required',
        'no_of_share_held' => 'required',

        'entity_permanent_address' => 'required_if:type,entity',
        'no_of_entity' => 'required_if:type,entity',
        'entity_correspondence_address' => 'required_if:type,entity',
        'entity_declaration' => 'required_if:type,entity',
        'authorized_personnel_name' => 'required_if:type,entity',
        'authorized_personnel_email' => 'required_if:type,entity',
        'authorized_personnel_mobile_number' => 'required_if:type,entity',
        'type_of_entity' => 'required_if:type,entity',
    ],
    'updateConnectedPersonDetails'=>[
        'type' => 'required',
        'name' => 'required',
        'nature_of_connection' => 'required',
        'pan_option' => 'required',
        'pan' =>'nullable|required_if:pan_option,Yes|size:10|regex:/^[A-Z]{5}\d{4}[A-Z]$/',
        // 'pan_attachment' =>'required_if:pan_option,Yes',
        // 'declaration_attachment' =>'required_if:pan_option,No',
        'permanent_address' => 'required_if:type,individual',
        'correspondence_address' => 'required_if:type,individual',
        'email' => 'required|string',
        'mobile' => 'required|string',
        'designation' => 'required_if:type,individual',
        'demat_account_number' => 'required',
        'no_of_share_held' => 'required',

        'entity_permanent_address' => 'required_if:type,entity',
        'no_of_entity' => 'required_if:type,entity',
        'entity_correspondence_address' => 'required_if:type,entity',
        'entity_declaration' => 'required_if:type,entity',
        'authorized_personnel_name' => 'required_if:type,entity',
        'authorized_personnel_email' => 'required_if:type,entity',
        'authorized_personnel_mobile_number' => 'required_if:type,entity',
        'type_of_entity' => 'required_if:type,entity',
    ],
    'saveCompanyData'=>[
        'company_name' => 'required|string|max:255',
        'registered_office' => 'required|string|max:255',
        'corporate_office' => 'required|string|max:255',
        'mobile' => 'required|string|max:20',
        'email' => 'required|string|email|max:255',
        'cin' => 'required|string|max:255',
        'isin' => 'required|string|max:255',
        'bse_scrip_code' => 'required|string|max:255',
        'nse_scrip_code' => 'required|string|max:255',
        'compliance_officer_name' => 'required|string|max:255',
        'compliance_officer_mail' => 'required|string|email|max:255',
        'compliance_officer_designation' => 'required|string|max:255',
    ],
    'saveImmediateRelativeDetails'   =>[
        'connected_person_id' => 'required|numeric',
        'relative_name' => 'required|string|max:255',

        'pan' =>'nullable|size:10|regex:/^[A-Z]{5}\d{4}[A-Z]$/|unique:relatives',
        'mobile' => 'nullable|string|max:20',
        'address' => 'nullable|string|max:255',
        'nature_of_relation' => 'required|string|max:255',
        'type_of_relation' => 'required_if:nature_of_relation,Other',
        'shares_held' => 'nullable|numeric',
        'demat_account_number' => 'nullable|string|max:50',
    ],
    'updateImmediateRelativeDetails'   =>[
        'connected_person_id' => 'required|numeric',
        'relative_name' => 'required|string|max:255',

        'pan' =>'nullable|size:10|regex:/^[A-Z]{5}\d{4}[A-Z]$/',
        'mobile' => 'nullable|string|max:20',
        'address' => 'nullable|string|max:255',
        'nature_of_relation' => 'required|string|max:255',
        'type_of_relation' => 'required_if:nature_of_relation,Other',
        'shares_held' => 'nullable|numeric',
        'demat_account_number' => 'nullable|string|max:50',
    ],
    'saveFinancialRelativeDetails'   =>[
        'connected_person_id' => 'required|numeric',
        'nature_of_relation' => 'required|string|max:255',
        'financial_relative_name' => 'required|string|max:255',
        'pan' => [
            'string',
            'size:10',
            'regex:/^[A-Z]{5}\d{4}[A-Z]$/',
            'unique:financial_relatives',
        ],
        'mobile' => 'required|string|max:20',
        'address' => 'required|string|max:255',
        'shares_held' => 'nullable|numeric',
        'demat_account_number' => 'required',
    ],
    'updateFinancialRelativeDetails'   =>[
        'connected_person_id' => 'required|numeric',
        'nature_of_relation' => 'required|string|max:255',
        'financial_relative_name' => 'required|string|max:255',
        'pan' => [
            'string',
            'size:10',
            'regex:/^[A-Z]{5}\d{4}[A-Z]$/',
        ],
        'mobile' => 'required|string|max:20',
        'address' => 'required|string|max:255',
        'shares_held' => 'nullable|numeric',
        'demat_account_number' => 'required',
    ],
    'systemCreatedUser'   =>[
        'firstname' => ['required', 'string', 'max:255'],
        'lastname'  => ['required', 'string', 'max:255'],
        'email'     => ['required', 'string', 'email', 'max:255', 'unique:'.User::class],
        'phone'     => ['required', 'min:10', 'max:12','regex:/[0-9]{9}/'],
        'designation'  => ['required', 'string', 'max:255'],
        'password'  => ['required', 'confirmed'],
    ],
    'updateUser'   =>[
        'firstname' => ['required', 'string', 'max:255'],
        'lastname'  => ['required', 'string', 'max:255'],
        'email'     => ['required', 'string', 'email', 'max:255'],
        'phone'     => ['required', 'min:10', 'max:12','regex:/[0-9]{9}/'],
        'designation'  => ['required', 'string', 'max:255'],
    ],

    'saveInsiderDetails'=>[
        'category_type' => 'required',
        'connected_person_id' => 'required_if:category_type,connected person',
        'type' => 'required_if:category_type,designated person',
        'name' => 'required_if:category_type,designated person',  
        'pan_option' => 'required_if:category_type,designated person',
        'pan' => 'required_if:pan_option,Yes|nullable|size:10|regex:/^[A-Z]{5}\d{4}[A-Z]$/|unique:connected_people',
        'pan_attachment' =>'required_if:pan_option,Yes',
        'declaration_attachment' =>'required_if:pan_option,No',
        'permanent_address' => 'required_if:type,individual',
        'correspondence_address' => 'required_if:type,individual',
        'nature_of_connection' => 'required_if:category_type,designated person',
        'email' => 'required_if:category_type,designated person',
        'mobile' => 'required_if:category_type,designated person',
        'designation' => 'required_if:type,individual',
        'demat_account_number' => 'required_if:category_type,designated person',
        'no_of_share_held' => 'required_if:category_type,designated person',

        'entity_permanent_address' => 'required_if:type,entity',
        'no_of_entity' => 'required_if:type,entity',
        'entity_correspondence_address' => 'required_if:type,entity',
        'type_of_entity' => 'required_if:type,entity',

        'entity_declaration' => 'required_if:type,entity',
        'authorized_personnel_name' => 'required_if:type,entity',
        'authorized_personnel_email' => 'required_if:type,entity',
        'authorized_personnel_mobile_number' => 'required_if:type,entity',
    ],
    
    'updateInsiderDetails'=>[
        'connected_person_id' => 'required_if:category_type,connected person',
        'type' => 'required',
        'name' => 'required',
        'pan_option' => 'required_if:category_type,designated person',
        'pan' => 'required_if:pan_option,Yes|nullable|size:10|regex:/^[A-Z]{5}\d{4}[A-Z]$/',
        // 'pan_attachment' =>'required_if:pan_option,Yes',
        // 'declaration_attachment' =>'required_if:pan_option,No',
        'permanent_address' => 'required_if:type,individual',
        'correspondence_address' => 'required_if:type,individual',
        'nature_of_connection' => 'required',
        'email' => 'required',
        'mobile' => 'required',
        'designation' => 'required_if:type,individual',
        'demat_account_number' => 'required',
        'no_of_share_held' => 'required',

        'entity_permanent_address' => 'required_if:type,entity',
        'no_of_entity' => 'required_if:type,entity',
        'type_of_entity' => 'required_if:type,entity',
        'entity_correspondence_address' => 'required_if:type,entity',
        'entity_declaration' => 'required_if:type,entity',
        'authorized_personnel_name' => 'required_if:type,entity',
        'authorized_personnel_email' => 'required_if:type,entity',
        'authorized_personnel_mobile_number' => 'required_if:type,entity',
    ],
    'saveUpsiDetail'=>[
        'sender_name' => 'required|string',
        'recipient_name' => 'required|string',
        'recipient_category' => 'required|string',
        'purpose_of_sharing' => 'required|string',
        'event_date' => 'required|date',
        'is_trading_window_open' => 'required|boolean',
        'closure_start_date' => 'nullable|date',
        'closure_end_date' => 'nullable|date|after:closure_start_date',
        'remarks' => 'nullable|string',
        'is_nda_signed' => 'required|boolean',
        'is_notice_of_confidentiality_shared' => 'required|boolean',
    ],
    'saveBreachUpsiDetails'=>[
        // 'upsi_id' => 'required',
        'insider_name' => 'required',
        'effect_of_breach' => 'required',
        'gain_or_loss' => 'required',
        'action_taken' => 'required',
        'breach_type' => 'required',
        'breach_details' => 'required',
        'reporting_date' => 'required',
        'status' => 'required',
        'action_taken' => 'required',
    ],
    'storeUPSI'=>[
        'upsi_sender_name' => 'required',
        'recipient_name' => 'required',
        'event_date' => 'required',


        'sharing_purpose' => 'required',
        'sharing_date' => 'required',
        'event_date' => 'required',
        'trading_window' => 'required'
    ],

];